app:
  version: v1.0.0

server:
  port: 8080
  forward-headers-strategy: native

spring:
  config:
    activate:
      on-profile: dev
  flyway:
    enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_ENDPOINT}:${MYSQL_PORT}/${MYSQL_DATABASE}?rewriteBatchedStatements=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: validate
  data:
    redis:
      host: localhost
      port: 6379
      ttl: 20
llm:
  active-provider: gemini
  gemini: # LLM Provider
    api-key: ${LLM_GEMINI_API_KEY}
    model: gemini-2.5-flash
    base-url: https://generativelanguage.googleapis.com/v1beta
    temperature: 0.7
    max-output-tokens: 10000

cors:
  allowed-origins: ${CORS_ALLOWED_ORIGINS}

jwt:
  token:
    secret-key: ${JWT_ACCESS_SECRET_KEY}
    expire-length: ${JWT_ACCESS_EXPIRATION}
  refresh:
    secret-key: ${JWT_REFRESH_SECRET_KEY}
    expire-length: ${JWT_REFRESH_EXPIRATION}

oauth:
  kakao:
    user-information-request-uri: https://kapi.kakao.com/v2/user/me
    access-token-request-uri: https://kauth.kakao.com/oauth/token
    rest-api-key: ${KAKAO_REST_API_KEY}
    client-secret: ${KAKAO_CLIENT_SECRET}

logging:
  config: classpath:log4j2/log4j2.xml

cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET}
      image-base-uri: ${AWS_IMAGE_BASE_URI}
      origin-storage-path: tour/
      temporary-storage-path: temporary/
      image-storage-path: images/

swagger:
  servers:
    local: ${SWAGGER_SERVERS_LOCAL}
    dev: ${SWAGGER_SERVERS_DEV}
    prod: ${SWAGGER_SERVERS_PROD}

management:
  health:
    redis:
      enabled: false
  metrics:
    tags:
      application: travelog
      env: dev
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics   # 웹으로 노출할 엔드포인트
  endpoint:
    metrics:
      access: read-only        # none | read-only | unrestricted
    prometheus:
      access: read-only
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTLP_TRACING_ENDPOINT}/v1/traces
