name: Backend CI for prod

on:
  pull_request:
    branches: [ "release-be" ]
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  integration-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    env:
      MYSQL_USERNAME: ${{ secrets.MYSQL_USERNAME }}
      MYSQL_USER_PASSWORD: ${{ secrets.MYSQL_USER_PASSWORD }}
      MYSQL_PORT: ${{ secrets.MYSQL_PORT }}
      MYSQL_DATABASE: ${{ secrets.MYSQL_DATABASE }}
      MYSQL_ENDPOINT: ${{ secrets.MYSQL_WRITER_ENDPOINT }}
      KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
      KAKAO_CLIENT_SECRET: ${{ secrets.KAKAO_CLIENT_SECRET }}
      JWT_REFRESH_SECRET_KEY: ${{ secrets.JWT_REFRESH_SECRET_KEY }}
      JWT_REFRESH_EXPIRATION: ${{ secrets.JWT_REFRESH_EXPIRATION }}
      JWT_ACCESS_SECRET_KEY: ${{ secrets.JWT_ACCESS_SECRET_KEY }}
      JWT_ACCESS_EXPIRATION: ${{ secrets.JWT_ACCESS_EXPIRATION }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_IMAGE_BASE_URI: ${{ secrets.AWS_IMAGE_BASE_URI }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Run tests
        run: ./gradlew test

      - name: Build with Gradle
        run: ./gradlew build -x test
      
